// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package validate

import (
	"context"
	"github.com/bobcob7/loam-refinery/internal/review"
	"sync"
)

// Ensure, that structuralCheckerMock does implement structuralChecker.
// If this is not the case, regenerate this file with moq.
var _ structuralChecker = &structuralCheckerMock{}

// structuralCheckerMock is a mock implementation of structuralChecker.
//
//	func TestSomethingThatUsesstructuralChecker(t *testing.T) {
//
//		// make and configure a mocked structuralChecker
//		mockedstructuralChecker := &structuralCheckerMock{
//			CheckFunc: func(doc *review.Document) []review.Diagnostic {
//				panic("mock out the Check method")
//			},
//		}
//
//		// use mockedstructuralChecker in code that requires structuralChecker
//		// and then make assertions.
//
//	}
type structuralCheckerMock struct {
	// CheckFunc mocks the Check method.
	CheckFunc func(doc *review.Document) []review.Diagnostic

	// calls tracks calls to the methods.
	calls struct {
		// Check holds details about calls to the Check method.
		Check []struct {
			// Doc is the doc argument value.
			Doc *review.Document
		}
	}
	lockCheck sync.RWMutex
}

// Check calls CheckFunc.
func (mock *structuralCheckerMock) Check(doc *review.Document) []review.Diagnostic {
	if mock.CheckFunc == nil {
		panic("structuralCheckerMock.CheckFunc: method is nil but structuralChecker.Check was just called")
	}
	callInfo := struct {
		Doc *review.Document
	}{
		Doc: doc,
	}
	mock.lockCheck.Lock()
	mock.calls.Check = append(mock.calls.Check, callInfo)
	mock.lockCheck.Unlock()
	return mock.CheckFunc(doc)
}

// CheckCalls gets all the calls that were made to Check.
// Check the length with:
//
//	len(mockedstructuralChecker.CheckCalls())
func (mock *structuralCheckerMock) CheckCalls() []struct {
	Doc *review.Document
} {
	var calls []struct {
		Doc *review.Document
	}
	mock.lockCheck.RLock()
	calls = mock.calls.Check
	mock.lockCheck.RUnlock()
	return calls
}

// Ensure, that advisoryRunnerMock does implement advisoryRunner.
// If this is not the case, regenerate this file with moq.
var _ advisoryRunner = &advisoryRunnerMock{}

// advisoryRunnerMock is a mock implementation of advisoryRunner.
//
//	func TestSomethingThatUsesadvisoryRunner(t *testing.T) {
//
//		// make and configure a mocked advisoryRunner
//		mockedadvisoryRunner := &advisoryRunnerMock{
//			RunFunc: func(doc *review.Document) ([]review.Diagnostic, []review.Skipped) {
//				panic("mock out the Run method")
//			},
//		}
//
//		// use mockedadvisoryRunner in code that requires advisoryRunner
//		// and then make assertions.
//
//	}
type advisoryRunnerMock struct {
	// RunFunc mocks the Run method.
	RunFunc func(doc *review.Document) ([]review.Diagnostic, []review.Skipped)

	// calls tracks calls to the methods.
	calls struct {
		// Run holds details about calls to the Run method.
		Run []struct {
			// Doc is the doc argument value.
			Doc *review.Document
		}
	}
	lockRun sync.RWMutex
}

// Run calls RunFunc.
func (mock *advisoryRunnerMock) Run(doc *review.Document) ([]review.Diagnostic, []review.Skipped) {
	if mock.RunFunc == nil {
		panic("advisoryRunnerMock.RunFunc: method is nil but advisoryRunner.Run was just called")
	}
	callInfo := struct {
		Doc *review.Document
	}{
		Doc: doc,
	}
	mock.lockRun.Lock()
	mock.calls.Run = append(mock.calls.Run, callInfo)
	mock.lockRun.Unlock()
	return mock.RunFunc(doc)
}

// RunCalls gets all the calls that were made to Run.
// Check the length with:
//
//	len(mockedadvisoryRunner.RunCalls())
func (mock *advisoryRunnerMock) RunCalls() []struct {
	Doc *review.Document
} {
	var calls []struct {
		Doc *review.Document
	}
	mock.lockRun.RLock()
	calls = mock.calls.Run
	mock.lockRun.RUnlock()
	return calls
}

// Ensure, that repositoryFinderMock does implement repositoryFinder.
// If this is not the case, regenerate this file with moq.
var _ repositoryFinder = &repositoryFinderMock{}

// repositoryFinderMock is a mock implementation of repositoryFinder.
//
//	func TestSomethingThatUsesrepositoryFinder(t *testing.T) {
//
//		// make and configure a mocked repositoryFinder
//		mockedrepositoryFinder := &repositoryFinderMock{
//			FindFunc: func(ctx context.Context, dir string) (verifier, error) {
//				panic("mock out the Find method")
//			},
//		}
//
//		// use mockedrepositoryFinder in code that requires repositoryFinder
//		// and then make assertions.
//
//	}
type repositoryFinderMock struct {
	// FindFunc mocks the Find method.
	FindFunc func(ctx context.Context, dir string) (verifier, error)

	// calls tracks calls to the methods.
	calls struct {
		// Find holds details about calls to the Find method.
		Find []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Dir is the dir argument value.
			Dir string
		}
	}
	lockFind sync.RWMutex
}

// Find calls FindFunc.
func (mock *repositoryFinderMock) Find(ctx context.Context, dir string) (verifier, error) {
	if mock.FindFunc == nil {
		panic("repositoryFinderMock.FindFunc: method is nil but repositoryFinder.Find was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Dir string
	}{
		Ctx: ctx,
		Dir: dir,
	}
	mock.lockFind.Lock()
	mock.calls.Find = append(mock.calls.Find, callInfo)
	mock.lockFind.Unlock()
	return mock.FindFunc(ctx, dir)
}

// FindCalls gets all the calls that were made to Find.
// Check the length with:
//
//	len(mockedrepositoryFinder.FindCalls())
func (mock *repositoryFinderMock) FindCalls() []struct {
	Ctx context.Context
	Dir string
} {
	var calls []struct {
		Ctx context.Context
		Dir string
	}
	mock.lockFind.RLock()
	calls = mock.calls.Find
	mock.lockFind.RUnlock()
	return calls
}

// Ensure, that verifierMock does implement verifier.
// If this is not the case, regenerate this file with moq.
var _ verifier = &verifierMock{}

// verifierMock is a mock implementation of verifier.
//
//	func TestSomethingThatUsesverifier(t *testing.T) {
//
//		// make and configure a mocked verifier
//		mockedverifier := &verifierMock{
//			VerifyFunc: func(ctx context.Context, doc *review.Document) ([]review.Diagnostic, []review.Skipped, review.Verification) {
//				panic("mock out the Verify method")
//			},
//		}
//
//		// use mockedverifier in code that requires verifier
//		// and then make assertions.
//
//	}
type verifierMock struct {
	// VerifyFunc mocks the Verify method.
	VerifyFunc func(ctx context.Context, doc *review.Document) ([]review.Diagnostic, []review.Skipped, review.Verification)

	// calls tracks calls to the methods.
	calls struct {
		// Verify holds details about calls to the Verify method.
		Verify []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Doc is the doc argument value.
			Doc *review.Document
		}
	}
	lockVerify sync.RWMutex
}

// Verify calls VerifyFunc.
func (mock *verifierMock) Verify(ctx context.Context, doc *review.Document) ([]review.Diagnostic, []review.Skipped, review.Verification) {
	if mock.VerifyFunc == nil {
		panic("verifierMock.VerifyFunc: method is nil but verifier.Verify was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Doc *review.Document
	}{
		Ctx: ctx,
		Doc: doc,
	}
	mock.lockVerify.Lock()
	mock.calls.Verify = append(mock.calls.Verify, callInfo)
	mock.lockVerify.Unlock()
	return mock.VerifyFunc(ctx, doc)
}

// VerifyCalls gets all the calls that were made to Verify.
// Check the length with:
//
//	len(mockedverifier.VerifyCalls())
func (mock *verifierMock) VerifyCalls() []struct {
	Ctx context.Context
	Doc *review.Document
} {
	var calls []struct {
		Ctx context.Context
		Doc *review.Document
	}
	mock.lockVerify.RLock()
	calls = mock.calls.Verify
	mock.lockVerify.RUnlock()
	return calls
}
