// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package cli

import (
	"context"
	"github.com/bobcob7/loam-refinery/internal/entry"
	"github.com/bobcob7/loam-refinery/internal/review"
	"github.com/bobcob7/loam-refinery/internal/validate"
	"io"
	"sync"
)

// Ensure, that documentValidatorMock does implement documentValidator.
// If this is not the case, regenerate this file with moq.
var _ documentValidator = &documentValidatorMock{}

// documentValidatorMock is a mock implementation of documentValidator.
//
//	func TestSomethingThatUsesdocumentValidator(t *testing.T) {
//
//		// make and configure a mocked documentValidator
//		mockeddocumentValidator := &documentValidatorMock{
//			ValidateFunc: func(ctx context.Context, source []byte, options validate.Options) (*review.Result, error) {
//				panic("mock out the Validate method")
//			},
//		}
//
//		// use mockeddocumentValidator in code that requires documentValidator
//		// and then make assertions.
//
//	}
type documentValidatorMock struct {
	// ValidateFunc mocks the Validate method.
	ValidateFunc func(ctx context.Context, source []byte, options validate.Options) (*review.Result, error)

	// calls tracks calls to the methods.
	calls struct {
		// Validate holds details about calls to the Validate method.
		Validate []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Source is the source argument value.
			Source []byte
			// Options is the options argument value.
			Options validate.Options
		}
	}
	lockValidate sync.RWMutex
}

// Validate calls ValidateFunc.
func (mock *documentValidatorMock) Validate(ctx context.Context, source []byte, options validate.Options) (*review.Result, error) {
	if mock.ValidateFunc == nil {
		panic("documentValidatorMock.ValidateFunc: method is nil but documentValidator.Validate was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Source  []byte
		Options validate.Options
	}{
		Ctx:     ctx,
		Source:  source,
		Options: options,
	}
	mock.lockValidate.Lock()
	mock.calls.Validate = append(mock.calls.Validate, callInfo)
	mock.lockValidate.Unlock()
	return mock.ValidateFunc(ctx, source, options)
}

// ValidateCalls gets all the calls that were made to Validate.
// Check the length with:
//
//	len(mockeddocumentValidator.ValidateCalls())
func (mock *documentValidatorMock) ValidateCalls() []struct {
	Ctx     context.Context
	Source  []byte
	Options validate.Options
} {
	var calls []struct {
		Ctx     context.Context
		Source  []byte
		Options validate.Options
	}
	mock.lockValidate.RLock()
	calls = mock.calls.Validate
	mock.lockValidate.RUnlock()
	return calls
}

// Ensure, that rendererMock does implement renderer.
// If this is not the case, regenerate this file with moq.
var _ renderer = &rendererMock{}

// rendererMock is a mock implementation of renderer.
//
//	func TestSomethingThatUsesrenderer(t *testing.T) {
//
//		// make and configure a mocked renderer
//		mockedrenderer := &rendererMock{
//			EntriesFunc: func(w io.Writer, entries []entry.Entry) error {
//				panic("mock out the Entries method")
//			},
//			IndexFunc: func(w io.Writer, groups []entry.Group) error {
//				panic("mock out the Index method")
//			},
//			ResultFunc: func(w io.Writer, result *review.Result) error {
//				panic("mock out the Result method")
//			},
//			SummaryFunc: func(w io.Writer, text string, groups []entry.Group) error {
//				panic("mock out the Summary method")
//			},
//		}
//
//		// use mockedrenderer in code that requires renderer
//		// and then make assertions.
//
//	}
type rendererMock struct {
	// EntriesFunc mocks the Entries method.
	EntriesFunc func(w io.Writer, entries []entry.Entry) error

	// IndexFunc mocks the Index method.
	IndexFunc func(w io.Writer, groups []entry.Group) error

	// ResultFunc mocks the Result method.
	ResultFunc func(w io.Writer, result *review.Result) error

	// SummaryFunc mocks the Summary method.
	SummaryFunc func(w io.Writer, text string, groups []entry.Group) error

	// calls tracks calls to the methods.
	calls struct {
		// Entries holds details about calls to the Entries method.
		Entries []struct {
			// W is the w argument value.
			W io.Writer
			// Entries is the entries argument value.
			Entries []entry.Entry
		}
		// Index holds details about calls to the Index method.
		Index []struct {
			// W is the w argument value.
			W io.Writer
			// Groups is the groups argument value.
			Groups []entry.Group
		}
		// Result holds details about calls to the Result method.
		Result []struct {
			// W is the w argument value.
			W io.Writer
			// Result is the result argument value.
			Result *review.Result
		}
		// Summary holds details about calls to the Summary method.
		Summary []struct {
			// W is the w argument value.
			W io.Writer
			// Text is the text argument value.
			Text string
			// Groups is the groups argument value.
			Groups []entry.Group
		}
	}
	lockEntries sync.RWMutex
	lockIndex   sync.RWMutex
	lockResult  sync.RWMutex
	lockSummary sync.RWMutex
}

// Entries calls EntriesFunc.
func (mock *rendererMock) Entries(w io.Writer, entries []entry.Entry) error {
	if mock.EntriesFunc == nil {
		panic("rendererMock.EntriesFunc: method is nil but renderer.Entries was just called")
	}
	callInfo := struct {
		W       io.Writer
		Entries []entry.Entry
	}{
		W:       w,
		Entries: entries,
	}
	mock.lockEntries.Lock()
	mock.calls.Entries = append(mock.calls.Entries, callInfo)
	mock.lockEntries.Unlock()
	return mock.EntriesFunc(w, entries)
}

// EntriesCalls gets all the calls that were made to Entries.
// Check the length with:
//
//	len(mockedrenderer.EntriesCalls())
func (mock *rendererMock) EntriesCalls() []struct {
	W       io.Writer
	Entries []entry.Entry
} {
	var calls []struct {
		W       io.Writer
		Entries []entry.Entry
	}
	mock.lockEntries.RLock()
	calls = mock.calls.Entries
	mock.lockEntries.RUnlock()
	return calls
}

// Index calls IndexFunc.
func (mock *rendererMock) Index(w io.Writer, groups []entry.Group) error {
	if mock.IndexFunc == nil {
		panic("rendererMock.IndexFunc: method is nil but renderer.Index was just called")
	}
	callInfo := struct {
		W      io.Writer
		Groups []entry.Group
	}{
		W:      w,
		Groups: groups,
	}
	mock.lockIndex.Lock()
	mock.calls.Index = append(mock.calls.Index, callInfo)
	mock.lockIndex.Unlock()
	return mock.IndexFunc(w, groups)
}

// IndexCalls gets all the calls that were made to Index.
// Check the length with:
//
//	len(mockedrenderer.IndexCalls())
func (mock *rendererMock) IndexCalls() []struct {
	W      io.Writer
	Groups []entry.Group
} {
	var calls []struct {
		W      io.Writer
		Groups []entry.Group
	}
	mock.lockIndex.RLock()
	calls = mock.calls.Index
	mock.lockIndex.RUnlock()
	return calls
}

// Result calls ResultFunc.
func (mock *rendererMock) Result(w io.Writer, result *review.Result) error {
	if mock.ResultFunc == nil {
		panic("rendererMock.ResultFunc: method is nil but renderer.Result was just called")
	}
	callInfo := struct {
		W      io.Writer
		Result *review.Result
	}{
		W:      w,
		Result: result,
	}
	mock.lockResult.Lock()
	mock.calls.Result = append(mock.calls.Result, callInfo)
	mock.lockResult.Unlock()
	return mock.ResultFunc(w, result)
}

// ResultCalls gets all the calls that were made to Result.
// Check the length with:
//
//	len(mockedrenderer.ResultCalls())
func (mock *rendererMock) ResultCalls() []struct {
	W      io.Writer
	Result *review.Result
} {
	var calls []struct {
		W      io.Writer
		Result *review.Result
	}
	mock.lockResult.RLock()
	calls = mock.calls.Result
	mock.lockResult.RUnlock()
	return calls
}

// Summary calls SummaryFunc.
func (mock *rendererMock) Summary(w io.Writer, text string, groups []entry.Group) error {
	if mock.SummaryFunc == nil {
		panic("rendererMock.SummaryFunc: method is nil but renderer.Summary was just called")
	}
	callInfo := struct {
		W      io.Writer
		Text   string
		Groups []entry.Group
	}{
		W:      w,
		Text:   text,
		Groups: groups,
	}
	mock.lockSummary.Lock()
	mock.calls.Summary = append(mock.calls.Summary, callInfo)
	mock.lockSummary.Unlock()
	return mock.SummaryFunc(w, text, groups)
}

// SummaryCalls gets all the calls that were made to Summary.
// Check the length with:
//
//	len(mockedrenderer.SummaryCalls())
func (mock *rendererMock) SummaryCalls() []struct {
	W      io.Writer
	Text   string
	Groups []entry.Group
} {
	var calls []struct {
		W      io.Writer
		Text   string
		Groups []entry.Group
	}
	mock.lockSummary.RLock()
	calls = mock.calls.Summary
	mock.lockSummary.RUnlock()
	return calls
}

// Ensure, that entryRegistryMock does implement entryRegistry.
// If this is not the case, regenerate this file with moq.
var _ entryRegistry = &entryRegistryMock{}

// entryRegistryMock is a mock implementation of entryRegistry.
//
//	func TestSomethingThatUsesentryRegistry(t *testing.T) {
//
//		// make and configure a mocked entryRegistry
//		mockedentryRegistry := &entryRegistryMock{
//			IndexFunc: func() []entry.Group {
//				panic("mock out the Index method")
//			},
//			ResolveFunc: func(name string) (entry.Entry, error) {
//				panic("mock out the Resolve method")
//			},
//		}
//
//		// use mockedentryRegistry in code that requires entryRegistry
//		// and then make assertions.
//
//	}
type entryRegistryMock struct {
	// IndexFunc mocks the Index method.
	IndexFunc func() []entry.Group

	// ResolveFunc mocks the Resolve method.
	ResolveFunc func(name string) (entry.Entry, error)

	// calls tracks calls to the methods.
	calls struct {
		// Index holds details about calls to the Index method.
		Index []struct {
		}
		// Resolve holds details about calls to the Resolve method.
		Resolve []struct {
			// Name is the name argument value.
			Name string
		}
	}
	lockIndex   sync.RWMutex
	lockResolve sync.RWMutex
}

// Index calls IndexFunc.
func (mock *entryRegistryMock) Index() []entry.Group {
	if mock.IndexFunc == nil {
		panic("entryRegistryMock.IndexFunc: method is nil but entryRegistry.Index was just called")
	}
	callInfo := struct {
	}{}
	mock.lockIndex.Lock()
	mock.calls.Index = append(mock.calls.Index, callInfo)
	mock.lockIndex.Unlock()
	return mock.IndexFunc()
}

// IndexCalls gets all the calls that were made to Index.
// Check the length with:
//
//	len(mockedentryRegistry.IndexCalls())
func (mock *entryRegistryMock) IndexCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockIndex.RLock()
	calls = mock.calls.Index
	mock.lockIndex.RUnlock()
	return calls
}

// Resolve calls ResolveFunc.
func (mock *entryRegistryMock) Resolve(name string) (entry.Entry, error) {
	if mock.ResolveFunc == nil {
		panic("entryRegistryMock.ResolveFunc: method is nil but entryRegistry.Resolve was just called")
	}
	callInfo := struct {
		Name string
	}{
		Name: name,
	}
	mock.lockResolve.Lock()
	mock.calls.Resolve = append(mock.calls.Resolve, callInfo)
	mock.lockResolve.Unlock()
	return mock.ResolveFunc(name)
}

// ResolveCalls gets all the calls that were made to Resolve.
// Check the length with:
//
//	len(mockedentryRegistry.ResolveCalls())
func (mock *entryRegistryMock) ResolveCalls() []struct {
	Name string
} {
	var calls []struct {
		Name string
	}
	mock.lockResolve.RLock()
	calls = mock.calls.Resolve
	mock.lockResolve.RUnlock()
	return calls
}

// Ensure, that documentStoreMock does implement documentStore.
// If this is not the case, regenerate this file with moq.
var _ documentStore = &documentStoreMock{}

// documentStoreMock is a mock implementation of documentStore.
//
//	func TestSomethingThatUsesdocumentStore(t *testing.T) {
//
//		// make and configure a mocked documentStore
//		mockeddocumentStore := &documentStoreMock{
//			SaveFunc: func(ctx context.Context, in StoreInput) error {
//				panic("mock out the Save method")
//			},
//		}
//
//		// use mockeddocumentStore in code that requires documentStore
//		// and then make assertions.
//
//	}
type documentStoreMock struct {
	// SaveFunc mocks the Save method.
	SaveFunc func(ctx context.Context, in StoreInput) error

	// calls tracks calls to the methods.
	calls struct {
		// Save holds details about calls to the Save method.
		Save []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// In is the in argument value.
			In StoreInput
		}
	}
	lockSave sync.RWMutex
}

// Save calls SaveFunc.
func (mock *documentStoreMock) Save(ctx context.Context, in StoreInput) error {
	if mock.SaveFunc == nil {
		panic("documentStoreMock.SaveFunc: method is nil but documentStore.Save was just called")
	}
	callInfo := struct {
		Ctx context.Context
		In  StoreInput
	}{
		Ctx: ctx,
		In:  in,
	}
	mock.lockSave.Lock()
	mock.calls.Save = append(mock.calls.Save, callInfo)
	mock.lockSave.Unlock()
	return mock.SaveFunc(ctx, in)
}

// SaveCalls gets all the calls that were made to Save.
// Check the length with:
//
//	len(mockeddocumentStore.SaveCalls())
func (mock *documentStoreMock) SaveCalls() []struct {
	Ctx context.Context
	In  StoreInput
} {
	var calls []struct {
		Ctx context.Context
		In  StoreInput
	}
	mock.lockSave.RLock()
	calls = mock.calls.Save
	mock.lockSave.RUnlock()
	return calls
}
