// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package cli

import (
	"context"
	"github.com/bobcob7/loam-refinery/internal/entry"
	"github.com/bobcob7/loam-refinery/internal/profile"
	"github.com/bobcob7/loam-refinery/internal/review"
	"github.com/bobcob7/loam-refinery/internal/store"
	"github.com/bobcob7/loam-refinery/internal/validate"
	"io"
	"sync"
)

// Ensure, that documentValidatorMock does implement documentValidator.
// If this is not the case, regenerate this file with moq.
var _ documentValidator = &documentValidatorMock{}

// documentValidatorMock is a mock implementation of documentValidator.
//
//	func TestSomethingThatUsesdocumentValidator(t *testing.T) {
//
//		// make and configure a mocked documentValidator
//		mockeddocumentValidator := &documentValidatorMock{
//			ValidateFunc: func(ctx context.Context, source []byte, options validate.Options) (*review.Result, error) {
//				panic("mock out the Validate method")
//			},
//		}
//
//		// use mockeddocumentValidator in code that requires documentValidator
//		// and then make assertions.
//
//	}
type documentValidatorMock struct {
	// ValidateFunc mocks the Validate method.
	ValidateFunc func(ctx context.Context, source []byte, options validate.Options) (*review.Result, error)

	// calls tracks calls to the methods.
	calls struct {
		// Validate holds details about calls to the Validate method.
		Validate []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Source is the source argument value.
			Source []byte
			// Options is the options argument value.
			Options validate.Options
		}
	}
	lockValidate sync.RWMutex
}

// Validate calls ValidateFunc.
func (mock *documentValidatorMock) Validate(ctx context.Context, source []byte, options validate.Options) (*review.Result, error) {
	if mock.ValidateFunc == nil {
		panic("documentValidatorMock.ValidateFunc: method is nil but documentValidator.Validate was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Source  []byte
		Options validate.Options
	}{
		Ctx:     ctx,
		Source:  source,
		Options: options,
	}
	mock.lockValidate.Lock()
	mock.calls.Validate = append(mock.calls.Validate, callInfo)
	mock.lockValidate.Unlock()
	return mock.ValidateFunc(ctx, source, options)
}

// ValidateCalls gets all the calls that were made to Validate.
// Check the length with:
//
//	len(mockeddocumentValidator.ValidateCalls())
func (mock *documentValidatorMock) ValidateCalls() []struct {
	Ctx     context.Context
	Source  []byte
	Options validate.Options
} {
	var calls []struct {
		Ctx     context.Context
		Source  []byte
		Options validate.Options
	}
	mock.lockValidate.RLock()
	calls = mock.calls.Validate
	mock.lockValidate.RUnlock()
	return calls
}

// Ensure, that rendererMock does implement renderer.
// If this is not the case, regenerate this file with moq.
var _ renderer = &rendererMock{}

// rendererMock is a mock implementation of renderer.
//
//	func TestSomethingThatUsesrenderer(t *testing.T) {
//
//		// make and configure a mocked renderer
//		mockedrenderer := &rendererMock{
//			EntriesFunc: func(w io.Writer, entries []entry.Entry) error {
//				panic("mock out the Entries method")
//			},
//			IndexFunc: func(w io.Writer, groups []entry.Group) error {
//				panic("mock out the Index method")
//			},
//			ProfilesFunc: func(w io.Writer, profiles []profile.Profile) error {
//				panic("mock out the Profiles method")
//			},
//			ResultFunc: func(w io.Writer, result *review.Result) error {
//				panic("mock out the Result method")
//			},
//			SummaryFunc: func(w io.Writer, text string, groups []entry.Group) error {
//				panic("mock out the Summary method")
//			},
//		}
//
//		// use mockedrenderer in code that requires renderer
//		// and then make assertions.
//
//	}
type rendererMock struct {
	// EntriesFunc mocks the Entries method.
	EntriesFunc func(w io.Writer, entries []entry.Entry) error

	// IndexFunc mocks the Index method.
	IndexFunc func(w io.Writer, groups []entry.Group) error

	// ProfilesFunc mocks the Profiles method.
	ProfilesFunc func(w io.Writer, profiles []profile.Profile) error

	// ResultFunc mocks the Result method.
	ResultFunc func(w io.Writer, result *review.Result) error

	// SummaryFunc mocks the Summary method.
	SummaryFunc func(w io.Writer, text string, groups []entry.Group) error

	// calls tracks calls to the methods.
	calls struct {
		// Entries holds details about calls to the Entries method.
		Entries []struct {
			// W is the w argument value.
			W io.Writer
			// Entries is the entries argument value.
			Entries []entry.Entry
		}
		// Index holds details about calls to the Index method.
		Index []struct {
			// W is the w argument value.
			W io.Writer
			// Groups is the groups argument value.
			Groups []entry.Group
		}
		// Profiles holds details about calls to the Profiles method.
		Profiles []struct {
			// W is the w argument value.
			W io.Writer
			// Profiles is the profiles argument value.
			Profiles []profile.Profile
		}
		// Result holds details about calls to the Result method.
		Result []struct {
			// W is the w argument value.
			W io.Writer
			// Result is the result argument value.
			Result *review.Result
		}
		// Summary holds details about calls to the Summary method.
		Summary []struct {
			// W is the w argument value.
			W io.Writer
			// Text is the text argument value.
			Text string
			// Groups is the groups argument value.
			Groups []entry.Group
		}
	}
	lockEntries  sync.RWMutex
	lockIndex    sync.RWMutex
	lockProfiles sync.RWMutex
	lockResult   sync.RWMutex
	lockSummary  sync.RWMutex
}

// Entries calls EntriesFunc.
func (mock *rendererMock) Entries(w io.Writer, entries []entry.Entry) error {
	if mock.EntriesFunc == nil {
		panic("rendererMock.EntriesFunc: method is nil but renderer.Entries was just called")
	}
	callInfo := struct {
		W       io.Writer
		Entries []entry.Entry
	}{
		W:       w,
		Entries: entries,
	}
	mock.lockEntries.Lock()
	mock.calls.Entries = append(mock.calls.Entries, callInfo)
	mock.lockEntries.Unlock()
	return mock.EntriesFunc(w, entries)
}

// EntriesCalls gets all the calls that were made to Entries.
// Check the length with:
//
//	len(mockedrenderer.EntriesCalls())
func (mock *rendererMock) EntriesCalls() []struct {
	W       io.Writer
	Entries []entry.Entry
} {
	var calls []struct {
		W       io.Writer
		Entries []entry.Entry
	}
	mock.lockEntries.RLock()
	calls = mock.calls.Entries
	mock.lockEntries.RUnlock()
	return calls
}

// Index calls IndexFunc.
func (mock *rendererMock) Index(w io.Writer, groups []entry.Group) error {
	if mock.IndexFunc == nil {
		panic("rendererMock.IndexFunc: method is nil but renderer.Index was just called")
	}
	callInfo := struct {
		W      io.Writer
		Groups []entry.Group
	}{
		W:      w,
		Groups: groups,
	}
	mock.lockIndex.Lock()
	mock.calls.Index = append(mock.calls.Index, callInfo)
	mock.lockIndex.Unlock()
	return mock.IndexFunc(w, groups)
}

// IndexCalls gets all the calls that were made to Index.
// Check the length with:
//
//	len(mockedrenderer.IndexCalls())
func (mock *rendererMock) IndexCalls() []struct {
	W      io.Writer
	Groups []entry.Group
} {
	var calls []struct {
		W      io.Writer
		Groups []entry.Group
	}
	mock.lockIndex.RLock()
	calls = mock.calls.Index
	mock.lockIndex.RUnlock()
	return calls
}

// Profiles calls ProfilesFunc.
func (mock *rendererMock) Profiles(w io.Writer, profiles []profile.Profile) error {
	if mock.ProfilesFunc == nil {
		panic("rendererMock.ProfilesFunc: method is nil but renderer.Profiles was just called")
	}
	callInfo := struct {
		W        io.Writer
		Profiles []profile.Profile
	}{
		W:        w,
		Profiles: profiles,
	}
	mock.lockProfiles.Lock()
	mock.calls.Profiles = append(mock.calls.Profiles, callInfo)
	mock.lockProfiles.Unlock()
	return mock.ProfilesFunc(w, profiles)
}

// ProfilesCalls gets all the calls that were made to Profiles.
// Check the length with:
//
//	len(mockedrenderer.ProfilesCalls())
func (mock *rendererMock) ProfilesCalls() []struct {
	W        io.Writer
	Profiles []profile.Profile
} {
	var calls []struct {
		W        io.Writer
		Profiles []profile.Profile
	}
	mock.lockProfiles.RLock()
	calls = mock.calls.Profiles
	mock.lockProfiles.RUnlock()
	return calls
}

// Result calls ResultFunc.
func (mock *rendererMock) Result(w io.Writer, result *review.Result) error {
	if mock.ResultFunc == nil {
		panic("rendererMock.ResultFunc: method is nil but renderer.Result was just called")
	}
	callInfo := struct {
		W      io.Writer
		Result *review.Result
	}{
		W:      w,
		Result: result,
	}
	mock.lockResult.Lock()
	mock.calls.Result = append(mock.calls.Result, callInfo)
	mock.lockResult.Unlock()
	return mock.ResultFunc(w, result)
}

// ResultCalls gets all the calls that were made to Result.
// Check the length with:
//
//	len(mockedrenderer.ResultCalls())
func (mock *rendererMock) ResultCalls() []struct {
	W      io.Writer
	Result *review.Result
} {
	var calls []struct {
		W      io.Writer
		Result *review.Result
	}
	mock.lockResult.RLock()
	calls = mock.calls.Result
	mock.lockResult.RUnlock()
	return calls
}

// Summary calls SummaryFunc.
func (mock *rendererMock) Summary(w io.Writer, text string, groups []entry.Group) error {
	if mock.SummaryFunc == nil {
		panic("rendererMock.SummaryFunc: method is nil but renderer.Summary was just called")
	}
	callInfo := struct {
		W      io.Writer
		Text   string
		Groups []entry.Group
	}{
		W:      w,
		Text:   text,
		Groups: groups,
	}
	mock.lockSummary.Lock()
	mock.calls.Summary = append(mock.calls.Summary, callInfo)
	mock.lockSummary.Unlock()
	return mock.SummaryFunc(w, text, groups)
}

// SummaryCalls gets all the calls that were made to Summary.
// Check the length with:
//
//	len(mockedrenderer.SummaryCalls())
func (mock *rendererMock) SummaryCalls() []struct {
	W      io.Writer
	Text   string
	Groups []entry.Group
} {
	var calls []struct {
		W      io.Writer
		Text   string
		Groups []entry.Group
	}
	mock.lockSummary.RLock()
	calls = mock.calls.Summary
	mock.lockSummary.RUnlock()
	return calls
}

// Ensure, that entryRegistryMock does implement entryRegistry.
// If this is not the case, regenerate this file with moq.
var _ entryRegistry = &entryRegistryMock{}

// entryRegistryMock is a mock implementation of entryRegistry.
//
//	func TestSomethingThatUsesentryRegistry(t *testing.T) {
//
//		// make and configure a mocked entryRegistry
//		mockedentryRegistry := &entryRegistryMock{
//			IndexFunc: func() []entry.Group {
//				panic("mock out the Index method")
//			},
//			ResolveFunc: func(name string) (entry.Entry, error) {
//				panic("mock out the Resolve method")
//			},
//		}
//
//		// use mockedentryRegistry in code that requires entryRegistry
//		// and then make assertions.
//
//	}
type entryRegistryMock struct {
	// IndexFunc mocks the Index method.
	IndexFunc func() []entry.Group

	// ResolveFunc mocks the Resolve method.
	ResolveFunc func(name string) (entry.Entry, error)

	// calls tracks calls to the methods.
	calls struct {
		// Index holds details about calls to the Index method.
		Index []struct {
		}
		// Resolve holds details about calls to the Resolve method.
		Resolve []struct {
			// Name is the name argument value.
			Name string
		}
	}
	lockIndex   sync.RWMutex
	lockResolve sync.RWMutex
}

// Index calls IndexFunc.
func (mock *entryRegistryMock) Index() []entry.Group {
	if mock.IndexFunc == nil {
		panic("entryRegistryMock.IndexFunc: method is nil but entryRegistry.Index was just called")
	}
	callInfo := struct {
	}{}
	mock.lockIndex.Lock()
	mock.calls.Index = append(mock.calls.Index, callInfo)
	mock.lockIndex.Unlock()
	return mock.IndexFunc()
}

// IndexCalls gets all the calls that were made to Index.
// Check the length with:
//
//	len(mockedentryRegistry.IndexCalls())
func (mock *entryRegistryMock) IndexCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockIndex.RLock()
	calls = mock.calls.Index
	mock.lockIndex.RUnlock()
	return calls
}

// Resolve calls ResolveFunc.
func (mock *entryRegistryMock) Resolve(name string) (entry.Entry, error) {
	if mock.ResolveFunc == nil {
		panic("entryRegistryMock.ResolveFunc: method is nil but entryRegistry.Resolve was just called")
	}
	callInfo := struct {
		Name string
	}{
		Name: name,
	}
	mock.lockResolve.Lock()
	mock.calls.Resolve = append(mock.calls.Resolve, callInfo)
	mock.lockResolve.Unlock()
	return mock.ResolveFunc(name)
}

// ResolveCalls gets all the calls that were made to Resolve.
// Check the length with:
//
//	len(mockedentryRegistry.ResolveCalls())
func (mock *entryRegistryMock) ResolveCalls() []struct {
	Name string
} {
	var calls []struct {
		Name string
	}
	mock.lockResolve.RLock()
	calls = mock.calls.Resolve
	mock.lockResolve.RUnlock()
	return calls
}

// Ensure, that documentStoreMock does implement documentStore.
// If this is not the case, regenerate this file with moq.
var _ documentStore = &documentStoreMock{}

// documentStoreMock is a mock implementation of documentStore.
//
//	func TestSomethingThatUsesdocumentStore(t *testing.T) {
//
//		// make and configure a mocked documentStore
//		mockeddocumentStore := &documentStoreMock{
//			SaveFunc: func(ctx context.Context, in StoreInput) error {
//				panic("mock out the Save method")
//			},
//		}
//
//		// use mockeddocumentStore in code that requires documentStore
//		// and then make assertions.
//
//	}
type documentStoreMock struct {
	// SaveFunc mocks the Save method.
	SaveFunc func(ctx context.Context, in StoreInput) error

	// calls tracks calls to the methods.
	calls struct {
		// Save holds details about calls to the Save method.
		Save []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// In is the in argument value.
			In StoreInput
		}
	}
	lockSave sync.RWMutex
}

// Save calls SaveFunc.
func (mock *documentStoreMock) Save(ctx context.Context, in StoreInput) error {
	if mock.SaveFunc == nil {
		panic("documentStoreMock.SaveFunc: method is nil but documentStore.Save was just called")
	}
	callInfo := struct {
		Ctx context.Context
		In  StoreInput
	}{
		Ctx: ctx,
		In:  in,
	}
	mock.lockSave.Lock()
	mock.calls.Save = append(mock.calls.Save, callInfo)
	mock.lockSave.Unlock()
	return mock.SaveFunc(ctx, in)
}

// SaveCalls gets all the calls that were made to Save.
// Check the length with:
//
//	len(mockeddocumentStore.SaveCalls())
func (mock *documentStoreMock) SaveCalls() []struct {
	Ctx context.Context
	In  StoreInput
} {
	var calls []struct {
		Ctx context.Context
		In  StoreInput
	}
	mock.lockSave.RLock()
	calls = mock.calls.Save
	mock.lockSave.RUnlock()
	return calls
}

// Ensure, that reviewStoreMock does implement reviewStore.
// If this is not the case, regenerate this file with moq.
var _ reviewStore = &reviewStoreMock{}

// reviewStoreMock is a mock implementation of reviewStore.
//
//	func TestSomethingThatUsesreviewStore(t *testing.T) {
//
//		// make and configure a mocked reviewStore
//		mockedreviewStore := &reviewStoreMock{
//			KnownFunc: func(ctx context.Context, repo string) (bool, error) {
//				panic("mock out the Known method")
//			},
//			ListFailedRunsFunc: func(ctx context.Context, repo string, ref string, limit int) ([]store.FailedRun, int, error) {
//				panic("mock out the ListFailedRuns method")
//			},
//			ListReposFunc: func(ctx context.Context) ([]store.RepoCount, error) {
//				panic("mock out the ListRepos method")
//			},
//			ListReviewsFunc: func(ctx context.Context, repo string, ref string, limit int) ([]store.Review, int, error) {
//				panic("mock out the ListReviews method")
//			},
//			ReadContentFunc: func(path string) ([]byte, error) {
//				panic("mock out the ReadContent method")
//			},
//			RepoNameFunc: func(ctx context.Context, dir string) (string, bool, error) {
//				panic("mock out the RepoName method")
//			},
//		}
//
//		// use mockedreviewStore in code that requires reviewStore
//		// and then make assertions.
//
//	}
type reviewStoreMock struct {
	// KnownFunc mocks the Known method.
	KnownFunc func(ctx context.Context, repo string) (bool, error)

	// ListFailedRunsFunc mocks the ListFailedRuns method.
	ListFailedRunsFunc func(ctx context.Context, repo string, ref string, limit int) ([]store.FailedRun, int, error)

	// ListReposFunc mocks the ListRepos method.
	ListReposFunc func(ctx context.Context) ([]store.RepoCount, error)

	// ListReviewsFunc mocks the ListReviews method.
	ListReviewsFunc func(ctx context.Context, repo string, ref string, limit int) ([]store.Review, int, error)

	// ReadContentFunc mocks the ReadContent method.
	ReadContentFunc func(path string) ([]byte, error)

	// RepoNameFunc mocks the RepoName method.
	RepoNameFunc func(ctx context.Context, dir string) (string, bool, error)

	// calls tracks calls to the methods.
	calls struct {
		// Known holds details about calls to the Known method.
		Known []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Repo is the repo argument value.
			Repo string
		}
		// ListFailedRuns holds details about calls to the ListFailedRuns method.
		ListFailedRuns []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Repo is the repo argument value.
			Repo string
			// Ref is the ref argument value.
			Ref string
			// Limit is the limit argument value.
			Limit int
		}
		// ListRepos holds details about calls to the ListRepos method.
		ListRepos []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// ListReviews holds details about calls to the ListReviews method.
		ListReviews []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Repo is the repo argument value.
			Repo string
			// Ref is the ref argument value.
			Ref string
			// Limit is the limit argument value.
			Limit int
		}
		// ReadContent holds details about calls to the ReadContent method.
		ReadContent []struct {
			// Path is the path argument value.
			Path string
		}
		// RepoName holds details about calls to the RepoName method.
		RepoName []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Dir is the dir argument value.
			Dir string
		}
	}
	lockKnown          sync.RWMutex
	lockListFailedRuns sync.RWMutex
	lockListRepos      sync.RWMutex
	lockListReviews    sync.RWMutex
	lockReadContent    sync.RWMutex
	lockRepoName       sync.RWMutex
}

// Known calls KnownFunc.
func (mock *reviewStoreMock) Known(ctx context.Context, repo string) (bool, error) {
	if mock.KnownFunc == nil {
		panic("reviewStoreMock.KnownFunc: method is nil but reviewStore.Known was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Repo string
	}{
		Ctx:  ctx,
		Repo: repo,
	}
	mock.lockKnown.Lock()
	mock.calls.Known = append(mock.calls.Known, callInfo)
	mock.lockKnown.Unlock()
	return mock.KnownFunc(ctx, repo)
}

// KnownCalls gets all the calls that were made to Known.
// Check the length with:
//
//	len(mockedreviewStore.KnownCalls())
func (mock *reviewStoreMock) KnownCalls() []struct {
	Ctx  context.Context
	Repo string
} {
	var calls []struct {
		Ctx  context.Context
		Repo string
	}
	mock.lockKnown.RLock()
	calls = mock.calls.Known
	mock.lockKnown.RUnlock()
	return calls
}

// ListFailedRuns calls ListFailedRunsFunc.
func (mock *reviewStoreMock) ListFailedRuns(ctx context.Context, repo string, ref string, limit int) ([]store.FailedRun, int, error) {
	if mock.ListFailedRunsFunc == nil {
		panic("reviewStoreMock.ListFailedRunsFunc: method is nil but reviewStore.ListFailedRuns was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Repo  string
		Ref   string
		Limit int
	}{
		Ctx:   ctx,
		Repo:  repo,
		Ref:   ref,
		Limit: limit,
	}
	mock.lockListFailedRuns.Lock()
	mock.calls.ListFailedRuns = append(mock.calls.ListFailedRuns, callInfo)
	mock.lockListFailedRuns.Unlock()
	return mock.ListFailedRunsFunc(ctx, repo, ref, limit)
}

// ListFailedRunsCalls gets all the calls that were made to ListFailedRuns.
// Check the length with:
//
//	len(mockedreviewStore.ListFailedRunsCalls())
func (mock *reviewStoreMock) ListFailedRunsCalls() []struct {
	Ctx   context.Context
	Repo  string
	Ref   string
	Limit int
} {
	var calls []struct {
		Ctx   context.Context
		Repo  string
		Ref   string
		Limit int
	}
	mock.lockListFailedRuns.RLock()
	calls = mock.calls.ListFailedRuns
	mock.lockListFailedRuns.RUnlock()
	return calls
}

// ListRepos calls ListReposFunc.
func (mock *reviewStoreMock) ListRepos(ctx context.Context) ([]store.RepoCount, error) {
	if mock.ListReposFunc == nil {
		panic("reviewStoreMock.ListReposFunc: method is nil but reviewStore.ListRepos was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockListRepos.Lock()
	mock.calls.ListRepos = append(mock.calls.ListRepos, callInfo)
	mock.lockListRepos.Unlock()
	return mock.ListReposFunc(ctx)
}

// ListReposCalls gets all the calls that were made to ListRepos.
// Check the length with:
//
//	len(mockedreviewStore.ListReposCalls())
func (mock *reviewStoreMock) ListReposCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockListRepos.RLock()
	calls = mock.calls.ListRepos
	mock.lockListRepos.RUnlock()
	return calls
}

// ListReviews calls ListReviewsFunc.
func (mock *reviewStoreMock) ListReviews(ctx context.Context, repo string, ref string, limit int) ([]store.Review, int, error) {
	if mock.ListReviewsFunc == nil {
		panic("reviewStoreMock.ListReviewsFunc: method is nil but reviewStore.ListReviews was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Repo  string
		Ref   string
		Limit int
	}{
		Ctx:   ctx,
		Repo:  repo,
		Ref:   ref,
		Limit: limit,
	}
	mock.lockListReviews.Lock()
	mock.calls.ListReviews = append(mock.calls.ListReviews, callInfo)
	mock.lockListReviews.Unlock()
	return mock.ListReviewsFunc(ctx, repo, ref, limit)
}

// ListReviewsCalls gets all the calls that were made to ListReviews.
// Check the length with:
//
//	len(mockedreviewStore.ListReviewsCalls())
func (mock *reviewStoreMock) ListReviewsCalls() []struct {
	Ctx   context.Context
	Repo  string
	Ref   string
	Limit int
} {
	var calls []struct {
		Ctx   context.Context
		Repo  string
		Ref   string
		Limit int
	}
	mock.lockListReviews.RLock()
	calls = mock.calls.ListReviews
	mock.lockListReviews.RUnlock()
	return calls
}

// ReadContent calls ReadContentFunc.
func (mock *reviewStoreMock) ReadContent(path string) ([]byte, error) {
	if mock.ReadContentFunc == nil {
		panic("reviewStoreMock.ReadContentFunc: method is nil but reviewStore.ReadContent was just called")
	}
	callInfo := struct {
		Path string
	}{
		Path: path,
	}
	mock.lockReadContent.Lock()
	mock.calls.ReadContent = append(mock.calls.ReadContent, callInfo)
	mock.lockReadContent.Unlock()
	return mock.ReadContentFunc(path)
}

// ReadContentCalls gets all the calls that were made to ReadContent.
// Check the length with:
//
//	len(mockedreviewStore.ReadContentCalls())
func (mock *reviewStoreMock) ReadContentCalls() []struct {
	Path string
} {
	var calls []struct {
		Path string
	}
	mock.lockReadContent.RLock()
	calls = mock.calls.ReadContent
	mock.lockReadContent.RUnlock()
	return calls
}

// RepoName calls RepoNameFunc.
func (mock *reviewStoreMock) RepoName(ctx context.Context, dir string) (string, bool, error) {
	if mock.RepoNameFunc == nil {
		panic("reviewStoreMock.RepoNameFunc: method is nil but reviewStore.RepoName was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Dir string
	}{
		Ctx: ctx,
		Dir: dir,
	}
	mock.lockRepoName.Lock()
	mock.calls.RepoName = append(mock.calls.RepoName, callInfo)
	mock.lockRepoName.Unlock()
	return mock.RepoNameFunc(ctx, dir)
}

// RepoNameCalls gets all the calls that were made to RepoName.
// Check the length with:
//
//	len(mockedreviewStore.RepoNameCalls())
func (mock *reviewStoreMock) RepoNameCalls() []struct {
	Ctx context.Context
	Dir string
} {
	var calls []struct {
		Ctx context.Context
		Dir string
	}
	mock.lockRepoName.RLock()
	calls = mock.calls.RepoName
	mock.lockRepoName.RUnlock()
	return calls
}

// Ensure, that profileSourceMock does implement profileSource.
// If this is not the case, regenerate this file with moq.
var _ profileSource = &profileSourceMock{}

// profileSourceMock is a mock implementation of profileSource.
//
//	func TestSomethingThatUsesprofileSource(t *testing.T) {
//
//		// make and configure a mocked profileSource
//		mockedprofileSource := &profileSourceMock{
//			ListFunc: func() ([]profile.Profile, []string, error) {
//				panic("mock out the List method")
//			},
//			LoadFunc: func(name string) (profile.Profile, bool, error) {
//				panic("mock out the Load method")
//			},
//		}
//
//		// use mockedprofileSource in code that requires profileSource
//		// and then make assertions.
//
//	}
type profileSourceMock struct {
	// ListFunc mocks the List method.
	ListFunc func() ([]profile.Profile, []string, error)

	// LoadFunc mocks the Load method.
	LoadFunc func(name string) (profile.Profile, bool, error)

	// calls tracks calls to the methods.
	calls struct {
		// List holds details about calls to the List method.
		List []struct {
		}
		// Load holds details about calls to the Load method.
		Load []struct {
			// Name is the name argument value.
			Name string
		}
	}
	lockList sync.RWMutex
	lockLoad sync.RWMutex
}

// List calls ListFunc.
func (mock *profileSourceMock) List() ([]profile.Profile, []string, error) {
	if mock.ListFunc == nil {
		panic("profileSourceMock.ListFunc: method is nil but profileSource.List was just called")
	}
	callInfo := struct {
	}{}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc()
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedprofileSource.ListCalls())
func (mock *profileSourceMock) ListCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// Load calls LoadFunc.
func (mock *profileSourceMock) Load(name string) (profile.Profile, bool, error) {
	if mock.LoadFunc == nil {
		panic("profileSourceMock.LoadFunc: method is nil but profileSource.Load was just called")
	}
	callInfo := struct {
		Name string
	}{
		Name: name,
	}
	mock.lockLoad.Lock()
	mock.calls.Load = append(mock.calls.Load, callInfo)
	mock.lockLoad.Unlock()
	return mock.LoadFunc(name)
}

// LoadCalls gets all the calls that were made to Load.
// Check the length with:
//
//	len(mockedprofileSource.LoadCalls())
func (mock *profileSourceMock) LoadCalls() []struct {
	Name string
} {
	var calls []struct {
		Name string
	}
	mock.lockLoad.RLock()
	calls = mock.calls.Load
	mock.lockLoad.RUnlock()
	return calls
}
