// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package collect

import (
	"context"
	"sync"
)

// Ensure, that readerMock does implement reader.
// If this is not the case, regenerate this file with moq.
var _ reader = &readerMock{}

// readerMock is a mock implementation of reader.
//
//	func TestSomethingThatUsesreader(t *testing.T) {
//
//		// make and configure a mocked reader
//		mockedreader := &readerMock{
//			ReadReviewFunc: func(ctx context.Context, digest string) ([]byte, error) {
//				panic("mock out the ReadReview method")
//			},
//		}
//
//		// use mockedreader in code that requires reader
//		// and then make assertions.
//
//	}
type readerMock struct {
	// ReadReviewFunc mocks the ReadReview method.
	ReadReviewFunc func(ctx context.Context, digest string) ([]byte, error)

	// calls tracks calls to the methods.
	calls struct {
		// ReadReview holds details about calls to the ReadReview method.
		ReadReview []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Digest is the digest argument value.
			Digest string
		}
	}
	lockReadReview sync.RWMutex
}

// ReadReview calls ReadReviewFunc.
func (mock *readerMock) ReadReview(ctx context.Context, digest string) ([]byte, error) {
	if mock.ReadReviewFunc == nil {
		panic("readerMock.ReadReviewFunc: method is nil but reader.ReadReview was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Digest string
	}{
		Ctx:    ctx,
		Digest: digest,
	}
	mock.lockReadReview.Lock()
	mock.calls.ReadReview = append(mock.calls.ReadReview, callInfo)
	mock.lockReadReview.Unlock()
	return mock.ReadReviewFunc(ctx, digest)
}

// ReadReviewCalls gets all the calls that were made to ReadReview.
// Check the length with:
//
//	len(mockedreader.ReadReviewCalls())
func (mock *readerMock) ReadReviewCalls() []struct {
	Ctx    context.Context
	Digest string
} {
	var calls []struct {
		Ctx    context.Context
		Digest string
	}
	mock.lockReadReview.RLock()
	calls = mock.calls.ReadReview
	mock.lockReadReview.RUnlock()
	return calls
}
