// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package store

import (
	"context"
	"sync"
	"time"
)

// Ensure, that clockMock does implement clock.
// If this is not the case, regenerate this file with moq.
var _ clock = &clockMock{}

// clockMock is a mock implementation of clock.
//
//	func TestSomethingThatUsesclock(t *testing.T) {
//
//		// make and configure a mocked clock
//		mockedclock := &clockMock{
//			NowFunc: func() time.Time {
//				panic("mock out the Now method")
//			},
//		}
//
//		// use mockedclock in code that requires clock
//		// and then make assertions.
//
//	}
type clockMock struct {
	// NowFunc mocks the Now method.
	NowFunc func() time.Time

	// calls tracks calls to the methods.
	calls struct {
		// Now holds details about calls to the Now method.
		Now []struct {
		}
	}
	lockNow sync.RWMutex
}

// Now calls NowFunc.
func (mock *clockMock) Now() time.Time {
	if mock.NowFunc == nil {
		panic("clockMock.NowFunc: method is nil but clock.Now was just called")
	}
	callInfo := struct {
	}{}
	mock.lockNow.Lock()
	mock.calls.Now = append(mock.calls.Now, callInfo)
	mock.lockNow.Unlock()
	return mock.NowFunc()
}

// NowCalls gets all the calls that were made to Now.
// Check the length with:
//
//	len(mockedclock.NowCalls())
func (mock *clockMock) NowCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockNow.RLock()
	calls = mock.calls.Now
	mock.lockNow.RUnlock()
	return calls
}

// Ensure, that gitRunnerMock does implement gitRunner.
// If this is not the case, regenerate this file with moq.
var _ gitRunner = &gitRunnerMock{}

// gitRunnerMock is a mock implementation of gitRunner.
//
//	func TestSomethingThatUsesgitRunner(t *testing.T) {
//
//		// make and configure a mocked gitRunner
//		mockedgitRunner := &gitRunnerMock{
//			originURLFunc: func(ctx context.Context, root string) (string, error) {
//				panic("mock out the originURL method")
//			},
//			rootFunc: func(ctx context.Context, dir string) (string, error) {
//				panic("mock out the root method")
//			},
//		}
//
//		// use mockedgitRunner in code that requires gitRunner
//		// and then make assertions.
//
//	}
type gitRunnerMock struct {
	// originURLFunc mocks the originURL method.
	originURLFunc func(ctx context.Context, root string) (string, error)

	// rootFunc mocks the root method.
	rootFunc func(ctx context.Context, dir string) (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// originURL holds details about calls to the originURL method.
		originURL []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Root is the root argument value.
			Root string
		}
		// root holds details about calls to the root method.
		root []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Dir is the dir argument value.
			Dir string
		}
	}
	lockoriginURL sync.RWMutex
	lockroot      sync.RWMutex
}

// originURL calls originURLFunc.
func (mock *gitRunnerMock) originURL(ctx context.Context, root string) (string, error) {
	if mock.originURLFunc == nil {
		panic("gitRunnerMock.originURLFunc: method is nil but gitRunner.originURL was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Root string
	}{
		Ctx:  ctx,
		Root: root,
	}
	mock.lockoriginURL.Lock()
	mock.calls.originURL = append(mock.calls.originURL, callInfo)
	mock.lockoriginURL.Unlock()
	return mock.originURLFunc(ctx, root)
}

// originURLCalls gets all the calls that were made to originURL.
// Check the length with:
//
//	len(mockedgitRunner.originURLCalls())
func (mock *gitRunnerMock) originURLCalls() []struct {
	Ctx  context.Context
	Root string
} {
	var calls []struct {
		Ctx  context.Context
		Root string
	}
	mock.lockoriginURL.RLock()
	calls = mock.calls.originURL
	mock.lockoriginURL.RUnlock()
	return calls
}

// root calls rootFunc.
func (mock *gitRunnerMock) root(ctx context.Context, dir string) (string, error) {
	if mock.rootFunc == nil {
		panic("gitRunnerMock.rootFunc: method is nil but gitRunner.root was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Dir string
	}{
		Ctx: ctx,
		Dir: dir,
	}
	mock.lockroot.Lock()
	mock.calls.root = append(mock.calls.root, callInfo)
	mock.lockroot.Unlock()
	return mock.rootFunc(ctx, dir)
}

// rootCalls gets all the calls that were made to root.
// Check the length with:
//
//	len(mockedgitRunner.rootCalls())
func (mock *gitRunnerMock) rootCalls() []struct {
	Ctx context.Context
	Dir string
} {
	var calls []struct {
		Ctx context.Context
		Dir string
	}
	mock.lockroot.RLock()
	calls = mock.calls.root
	mock.lockroot.RUnlock()
	return calls
}
