// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
)

type Run struct {
	ID            int64
	At            string
	Repo          string
	Ref           sql.NullString
	Digest        string
	ExitCode      int64
	Verdict       sql.NullString
	Assessment    sql.NullString
	NumComments   sql.NullInt64
	NumErrors     sql.NullInt64
	NumAdvisories sql.NullInt64
	NumSkipped    sql.NullInt64
	ToolVersion   string
	SchemaVersion string
}
