// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countFailedRuns = `-- name: CountFailedRuns :one
SELECT count(*) FROM runs
WHERE repo = ?1
  AND exit_code != 0
  AND (?2 IS NULL OR ref = ?2)
`

type CountFailedRunsParams struct {
	Repo string
	Ref  interface{}
}

// Rows matching ListFailedRuns before its LIMIT.
func (q *Queries) CountFailedRuns(ctx context.Context, arg CountFailedRunsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFailedRuns, arg.Repo, arg.Ref)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countReviews = `-- name: CountReviews :one
SELECT count(*) FROM runs
WHERE repo = ?1
  AND exit_code = 0
  AND (?2 IS NULL OR ref = ?2)
`

type CountReviewsParams struct {
	Repo string
	Ref  interface{}
}

// Rows matching ListReviews before its LIMIT, so a caller can tell a
// truncated answer from a complete one (config.md section 6.1).
func (q *Queries) CountReviews(ctx context.Context, arg CountReviewsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countReviews, arg.Repo, arg.Ref)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertRun = `-- name: InsertRun :one
INSERT INTO runs (
  at, repo, ref, digest, exit_code, verdict, assessment,
  num_comments, num_errors, num_advisories, num_skipped,
  tool_version, schema_version
) VALUES (
  ?1, ?2, ?3, ?4, ?5, ?6, ?7,
  ?8, ?9, ?10, ?11,
  ?12, ?13
)
RETURNING id, at, repo, ref, digest, exit_code, verdict, assessment,
  num_comments, num_errors, num_advisories, num_skipped,
  tool_version, schema_version
`

type InsertRunParams struct {
	At            string
	Repo          string
	Ref           sql.NullString
	Digest        string
	ExitCode      int64
	Verdict       sql.NullString
	Assessment    sql.NullString
	NumComments   sql.NullInt64
	NumErrors     sql.NullInt64
	NumAdvisories sql.NullInt64
	NumSkipped    sql.NullInt64
	ToolVersion   string
	SchemaVersion string
}

func (q *Queries) InsertRun(ctx context.Context, arg InsertRunParams) (Run, error) {
	row := q.db.QueryRowContext(ctx, insertRun,
		arg.At,
		arg.Repo,
		arg.Ref,
		arg.Digest,
		arg.ExitCode,
		arg.Verdict,
		arg.Assessment,
		arg.NumComments,
		arg.NumErrors,
		arg.NumAdvisories,
		arg.NumSkipped,
		arg.ToolVersion,
		arg.SchemaVersion,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.At,
		&i.Repo,
		&i.Ref,
		&i.Digest,
		&i.ExitCode,
		&i.Verdict,
		&i.Assessment,
		&i.NumComments,
		&i.NumErrors,
		&i.NumAdvisories,
		&i.NumSkipped,
		&i.ToolVersion,
		&i.SchemaVersion,
	)
	return i, err
}

const listDistinctDigests = `-- name: ListDistinctDigests :many
SELECT digest, CAST(min(at) AS TEXT) AS at FROM runs
WHERE repo = ?1
  AND ref = ?2
  AND exit_code = 0
GROUP BY digest
ORDER BY at ASC
`

type ListDistinctDigestsParams struct {
	Repo string
	Ref  sql.NullString
}

type ListDistinctDigestsRow struct {
	Digest string
	At     string
}

// Distinct digests among passing runs for one repo and ref, each paired
// with the earliest at among the rows that share it (combined-reviews.md
// section 5.3.1). Reads the index config.md section 4.5.1 already builds
// for repo+ref (runs_repo_ref) and digest (runs_digest). Ordered oldest
// first.
func (q *Queries) ListDistinctDigests(ctx context.Context, arg ListDistinctDigestsParams) ([]ListDistinctDigestsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDistinctDigests, arg.Repo, arg.Ref)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDistinctDigestsRow
	for rows.Next() {
		var i ListDistinctDigestsRow
		if err := rows.Scan(&i.Digest, &i.At); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFailedRuns = `-- name: ListFailedRuns :many
SELECT id, at, repo, ref, digest, exit_code, verdict, assessment, num_comments, num_errors, num_advisories, num_skipped, tool_version, schema_version FROM runs
WHERE repo = ?1
  AND exit_code != 0
  AND (?2 IS NULL OR ref = ?2)
ORDER BY at DESC
LIMIT ?3
`

type ListFailedRunsParams struct {
	Repo  string
	Ref   interface{}
	Limit int64
}

// The other half of the log: runs that stored no review (--failed).
func (q *Queries) ListFailedRuns(ctx context.Context, arg ListFailedRunsParams) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, listFailedRuns, arg.Repo, arg.Ref, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.At,
			&i.Repo,
			&i.Ref,
			&i.Digest,
			&i.ExitCode,
			&i.Verdict,
			&i.Assessment,
			&i.NumComments,
			&i.NumErrors,
			&i.NumAdvisories,
			&i.NumSkipped,
			&i.ToolVersion,
			&i.SchemaVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepoCounts = `-- name: ListRepoCounts :many
SELECT
  repo,
  sum(CASE WHEN exit_code = 0 THEN 1 ELSE 0 END) AS reviews,
  sum(CASE WHEN exit_code != 0 THEN 1 ELSE 0 END) AS failed
FROM runs
GROUP BY repo
ORDER BY repo
`

type ListRepoCountsRow struct {
	Repo    string
	Reviews sql.NullFloat64
	Failed  sql.NullFloat64
}

// Per-repository counts of stored reviews and failed runs, for --list.
// Ordered by repo so the output is stable between runs.
func (q *Queries) ListRepoCounts(ctx context.Context) ([]ListRepoCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRepoCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRepoCountsRow
	for rows.Next() {
		var i ListRepoCountsRow
		if err := rows.Scan(&i.Repo, &i.Reviews, &i.Failed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviews = `-- name: ListReviews :many
SELECT id, at, repo, ref, digest, exit_code, verdict, assessment, num_comments, num_errors, num_advisories, num_skipped, tool_version, schema_version FROM runs
WHERE repo = ?1
  AND exit_code = 0
  AND (?2 IS NULL OR ref = ?2)
ORDER BY at DESC
LIMIT ?3
`

type ListReviewsParams struct {
	Repo  string
	Ref   interface{}
	Limit int64
}

// Newest first, limited. LIMIT accepts -1 for "no limit" (config.md
// section 6, --limit=0).
func (q *Queries) ListReviews(ctx context.Context, arg ListReviewsParams) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, listReviews, arg.Repo, arg.Ref, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.At,
			&i.Repo,
			&i.Ref,
			&i.Digest,
			&i.ExitCode,
			&i.Verdict,
			&i.Assessment,
			&i.NumComments,
			&i.NumErrors,
			&i.NumAdvisories,
			&i.NumSkipped,
			&i.ToolVersion,
			&i.SchemaVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const repoKnown = `-- name: RepoKnown :one
SELECT EXISTS(SELECT 1 FROM runs WHERE repo = ?1) AS known
`

// Whether the store has any row at all for repo, regardless of exit code.
// Distinguishes a mistyped --repo from one that is known but empty
// (config.md section 6.2).
func (q *Queries) RepoKnown(ctx context.Context, repo string) (bool, error) {
	row := q.db.QueryRowContext(ctx, repoKnown, repo)
	var known bool
	err := row.Scan(&known)
	return known, err
}
