// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package verify

import (
	"context"
	"sync"
)

// Ensure, that gitRunnerMock does implement gitRunner.
// If this is not the case, regenerate this file with moq.
var _ gitRunner = &gitRunnerMock{}

// gitRunnerMock is a mock implementation of gitRunner.
//
//	func TestSomethingThatUsesgitRunner(t *testing.T) {
//
//		// make and configure a mocked gitRunner
//		mockedgitRunner := &gitRunnerMock{
//			runFunc: func(ctx context.Context, args ...string) ([]byte, error) {
//				panic("mock out the run method")
//			},
//		}
//
//		// use mockedgitRunner in code that requires gitRunner
//		// and then make assertions.
//
//	}
type gitRunnerMock struct {
	// runFunc mocks the run method.
	runFunc func(ctx context.Context, args ...string) ([]byte, error)

	// calls tracks calls to the methods.
	calls struct {
		// run holds details about calls to the run method.
		run []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Args is the args argument value.
			Args []string
		}
	}
	lockrun sync.RWMutex
}

// run calls runFunc.
func (mock *gitRunnerMock) run(ctx context.Context, args ...string) ([]byte, error) {
	if mock.runFunc == nil {
		panic("gitRunnerMock.runFunc: method is nil but gitRunner.run was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Args []string
	}{
		Ctx:  ctx,
		Args: args,
	}
	mock.lockrun.Lock()
	mock.calls.run = append(mock.calls.run, callInfo)
	mock.lockrun.Unlock()
	return mock.runFunc(ctx, args...)
}

// runCalls gets all the calls that were made to run.
// Check the length with:
//
//	len(mockedgitRunner.runCalls())
func (mock *gitRunnerMock) runCalls() []struct {
	Ctx  context.Context
	Args []string
} {
	var calls []struct {
		Ctx  context.Context
		Args []string
	}
	mock.lockrun.RLock()
	calls = mock.calls.run
	mock.lockrun.RUnlock()
	return calls
}
