// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package verify

import (
	"context"
	"sync"
)

// Ensure, that gitRunnerMock does implement gitRunner.
// If this is not the case, regenerate this file with moq.
var _ gitRunner = &gitRunnerMock{}

// gitRunnerMock is a mock implementation of gitRunner.
//
//	func TestSomethingThatUsesgitRunner(t *testing.T) {
//
//		// make and configure a mocked gitRunner
//		mockedgitRunner := &gitRunnerMock{
//			runFunc: func(ctx context.Context, args ...string) ([]byte, error) {
//				panic("mock out the run method")
//			},
//			worktreeDivergedFunc: func(ctx context.Context, ref string, path string) (bool, error) {
//				panic("mock out the worktreeDiverged method")
//			},
//		}
//
//		// use mockedgitRunner in code that requires gitRunner
//		// and then make assertions.
//
//	}
type gitRunnerMock struct {
	// runFunc mocks the run method.
	runFunc func(ctx context.Context, args ...string) ([]byte, error)

	// worktreeDivergedFunc mocks the worktreeDiverged method.
	worktreeDivergedFunc func(ctx context.Context, ref string, path string) (bool, error)

	// calls tracks calls to the methods.
	calls struct {
		// run holds details about calls to the run method.
		run []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Args is the args argument value.
			Args []string
		}
		// worktreeDiverged holds details about calls to the worktreeDiverged method.
		worktreeDiverged []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ref is the ref argument value.
			Ref string
			// Path is the path argument value.
			Path string
		}
	}
	lockrun              sync.RWMutex
	lockworktreeDiverged sync.RWMutex
}

// run calls runFunc.
func (mock *gitRunnerMock) run(ctx context.Context, args ...string) ([]byte, error) {
	if mock.runFunc == nil {
		panic("gitRunnerMock.runFunc: method is nil but gitRunner.run was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Args []string
	}{
		Ctx:  ctx,
		Args: args,
	}
	mock.lockrun.Lock()
	mock.calls.run = append(mock.calls.run, callInfo)
	mock.lockrun.Unlock()
	return mock.runFunc(ctx, args...)
}

// runCalls gets all the calls that were made to run.
// Check the length with:
//
//	len(mockedgitRunner.runCalls())
func (mock *gitRunnerMock) runCalls() []struct {
	Ctx  context.Context
	Args []string
} {
	var calls []struct {
		Ctx  context.Context
		Args []string
	}
	mock.lockrun.RLock()
	calls = mock.calls.run
	mock.lockrun.RUnlock()
	return calls
}

// worktreeDiverged calls worktreeDivergedFunc.
func (mock *gitRunnerMock) worktreeDiverged(ctx context.Context, ref string, path string) (bool, error) {
	if mock.worktreeDivergedFunc == nil {
		panic("gitRunnerMock.worktreeDivergedFunc: method is nil but gitRunner.worktreeDiverged was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Ref  string
		Path string
	}{
		Ctx:  ctx,
		Ref:  ref,
		Path: path,
	}
	mock.lockworktreeDiverged.Lock()
	mock.calls.worktreeDiverged = append(mock.calls.worktreeDiverged, callInfo)
	mock.lockworktreeDiverged.Unlock()
	return mock.worktreeDivergedFunc(ctx, ref, path)
}

// worktreeDivergedCalls gets all the calls that were made to worktreeDiverged.
// Check the length with:
//
//	len(mockedgitRunner.worktreeDivergedCalls())
func (mock *gitRunnerMock) worktreeDivergedCalls() []struct {
	Ctx  context.Context
	Ref  string
	Path string
} {
	var calls []struct {
		Ctx  context.Context
		Ref  string
		Path string
	}
	mock.lockworktreeDiverged.RLock()
	calls = mock.calls.worktreeDiverged
	mock.lockworktreeDiverged.RUnlock()
	return calls
}
